// =======================
// PoE2 Farm Calculator - Stable UI + No PointerEvent bug
// Uses data/prices.json generated by scraper
// =======================

let allItems = [];           // full lines from prices.json
let byName = new Map();      // nameLower -> item
let activeSection = "currency";

let exaltIcon = "";
let divineIcon = "";
let divineExValue = null;    // 1 Divine = X Exalted (from prices.json)

const SECTIONS = [
  { id:"currency", label:"Currency" },
  { id:"fragments", label:"Fragments" },
  { id:"abyssalBones", label:"Abyssal Bones" },
  { id:"uncutGems", label:"Uncut Gems" },
  { id:"lineageGems", label:"Lineage Gems" },
  { id:"essences", label:"Essences" },
  { id:"soulCores", label:"Soul Cores" },
  { id:"idols", label:"Idols" },
  { id:"runes", label:"Runes" },
  { id:"omens", label:"Omens" },
  { id:"expedition", label:"Expedition" },
  { id:"liquidEmotions", label:"Liquid Emotions" },
  { id:"catalyst", label:"Catalyst" },
];

function setStatus(msg){
  const el = document.getElementById("fetchStatus");
  if (el) el.textContent = msg;
  console.log(msg);
}

function cleanName(s){
  return String(s || "").replace(/\s*WIKI\s*$/i, "").trim();
}

function num(id){
  const el = document.getElementById(id);
  const v = el ? Number(el.value) : 0;
  return Number.isFinite(v) ? v : 0;
}

function escapeHtml(s){
  return String(s).replace(/[&<>"']/g, m => ({
    "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"
  }[m]));
}

// ✅ No commas: always show numbers with DOT
function fmt2(n){
  const x = Number(n || 0);
  return x.toFixed(2);
}

// totals show Ex/Div both
function formatDual(exVal){
  const ex = Number(exVal || 0);
  const div = (divineExValue && divineExValue > 0) ? (ex / divineExValue) : 0;

  return `
    <span>${fmt2(ex)}</span>${exaltIcon ? `<img class="pIcon" src="${exaltIcon}" alt="">` : ""}
    <span style="opacity:.6">/</span>
    <span>${fmt2(div)}</span>${divineIcon ? `<img class="pIcon" src="${divineIcon}" alt="">` : ""}
  `;
}

async function loadData(){
  try{
    setStatus("Status: loading data/prices.json...");
    const res = await fetch("./data/prices.json?ts=" + Date.now(), { cache:"no-store" });
    const data = await res.json();

    allItems = (data.lines || []).map(x => ({
      section: x.section || "currency",
      name: cleanName(x.name),
      icon: x.icon || "",
      amount: Number(x.amount ?? 0),   // already exalted in your new plan
      unit: x.unit || "",
      unitIcon: x.unitIcon || "",
    }));

    byName = new Map(allItems.map(it => [it.name.toLowerCase(), it]));

    exaltIcon = data.baseIcon || "";
    const divRow = byName.get("divine orb");
    divineIcon = divRow?.icon || "";
    // IMPORTANT: in your new approach, Divine Orb "amount" should be 1.00 in Exalted display page
    // but we still store its exalted value as amount (Ex)
    // Divine should have amount == 1.00 if values are "in Divine", so instead we set divineExValue using the row "Chaos Orb" etc...
    // Here we assume: prices.json stores values in Exalted => then Divine Orb amount = X (Ex per Divine)
    divineExValue = divRow ? Number(divRow.amount || 0) : null;

    setStatus(`Status: OK ✅ sections=${SECTIONS.length} items=${allItems.length} | 1 Div=${divineExValue ?? "?"} Ex`);

    buildTabs();
    fillDatalist();
    renderMarket();
    loadState();

    // ensure at least one loot row
    if (!document.querySelector("#lootBody tr")) addLootRow();
    recalcAll();

  }catch(e){
    setStatus("Status: ERROR ❌ " + e.toString());
  }
}

function buildTabs(){
  const wrap = document.getElementById("tabs");
  if (!wrap) return;

  wrap.innerHTML = "";
  SECTIONS.forEach(sec => {
    const b = document.createElement("button");
    b.className = "tab" + (sec.id === activeSection ? " active" : "");
    b.textContent = sec.label;
    b.dataset.tab = sec.id;

    b.addEventListener("click", () => {
      activeSection = sec.id;
      document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
      renderMarket();
      saveState();
    });

    wrap.appendChild(b);
  });
}

function fillDatalist(){
  const dl = document.getElementById("itemDatalist");
  if (!dl) return;

  dl.innerHTML = "";
  allItems.forEach(it => {
    const opt = document.createElement("option");
    opt.value = it.name;
    dl.appendChild(opt);
  });
}

function renderMarket(){
  const list = document.getElementById("marketList");
  if (!list) return;

  const q = (document.getElementById("marketSearch")?.value || "").trim().toLowerCase();

  const filtered = allItems
    .filter(it => it.section === activeSection)
    .filter(it => it.name.toLowerCase().includes(q))
    .slice(0, 300);

  list.innerHTML = "";

  if (!filtered.length){
    list.innerHTML = `<div style="color:#bbb;padding:10px;">No items.</div>`;
    return;
  }

  filtered.forEach(it => {
    const row = document.createElement("div");
    row.className = "market-row";

    // ✅ add ⇄ between name and price
    row.innerHTML = `
      <div class="mLeft">
        ${it.icon ? `<img class="cIcon" src="${it.icon}" alt="">` : ""}
        <span class="mName">${escapeHtml(it.name)}</span>
      </div>

      <div class="mArrow">⇄</div>

      <div class="mRight">
        <span>${fmt2(it.amount)}</span>
        ${exaltIcon ? `<img class="unitIcon" src="${exaltIcon}" alt="">` : ""}
      </div>
    `;

    row.addEventListener("click", () => addLootRow(it.name));
    list.appendChild(row);
  });
}

// ✅ FIXED: will never put PointerEvent into input
function addLootRow(prefillName = ""){
  if (prefillName && typeof prefillName === "object") prefillName = "";
  prefillName = String(prefillName || "");

  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <img class="lootIcon" alt="">
        <input class="lootItem" list="itemDatalist" placeholder="Item">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <span class="lootPrice">0.00</span>
        ${exaltIcon ? `<img class="baseIcon" src="${exaltIcon}" alt="">` : ""}
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus" aria-label="Minus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus" aria-label="Plus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const itemInput = tr.querySelector(".lootItem");
  const qtyInput  = tr.querySelector(".lootQty");
  const iconImg   = tr.querySelector(".lootIcon");
  const priceSpan = tr.querySelector(".lootPrice");

  itemInput.value = prefillName;

  function applyPrice(){
    const name = (itemInput.value || "").trim().toLowerCase();
    const found = byName.get(name);

    if (found?.icon){
      iconImg.src = found.icon;
      iconImg.style.display = "block";
    } else {
      iconImg.style.display = "none";
    }

    // prices shown in Exalted
    priceSpan.textContent = fmt2(found ? found.amount : 0);
  }

  applyPrice();
  recalcAll();
  saveState();

  itemInput.addEventListener("input", () => {
    applyPrice();
    recalcAll();
    saveState();
  });

  qtyInput.addEventListener("input", () => {
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    recalcAll();
    saveState();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    recalcAll();
    saveState();
  });
}

function addManualRow(){
  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow manualRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <img class="lootIcon" style="display:none" alt="">
        <input class="lootItem" placeholder="Custom item">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <input class="manualPrice" type="number" value="0" min="0" step="0.01">
        ${exaltIcon ? `<img class="baseIcon" src="${exaltIcon}" alt="">` : ""}
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const qtyInput = tr.querySelector(".lootQty");
  const priceInput = tr.querySelector(".manualPrice");

  const update = () => { recalcAll(); saveState(); };

  qtyInput.addEventListener("input", update);
  priceInput.addEventListener("input", update);

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    update();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    update();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    update();
  });

  update();
}

function calcInvestEx(){
  return num("maps") * num("costPerMap");
}

function calcLootEx(){
  let total = 0;
  document.querySelectorAll("#lootBody tr").forEach(tr => {
    const qty = Number(tr.querySelector(".lootQty")?.value || 0);

    if (tr.classList.contains("manualRow")){
      const p = Number(tr.querySelector(".manualPrice")?.value || 0);
      total += p * qty;
    } else {
      const p = Number(tr.querySelector(".lootPrice")?.textContent || 0);
      total += p * qty;
    }
  });
  return total;
}

function recalcAll(){
  const invest = calcInvestEx();
  const loot = calcLootEx();
  const gain = loot - invest;

  document.getElementById("totalInvest").innerHTML = formatDual(invest);
  document.getElementById("totalLoot").innerHTML = formatDual(loot);
  document.getElementById("gain").innerHTML = formatDual(gain);
}

function saveState(){
  const rows = [...document.querySelectorAll("#lootBody tr")].map(tr => {
    const manual = tr.classList.contains("manualRow");
    return {
      manual,
      item: tr.querySelector(".lootItem")?.value || "",
      qty: tr.querySelector(".lootQty")?.value ?? "0",
      price: manual ? (tr.querySelector(".manualPrice")?.value ?? "0") : null
    };
  });

  const state = {
    activeSection,
    search: document.getElementById("marketSearch")?.value ?? "",
    maps: document.getElementById("maps")?.value ?? "10",
    costPerMap: document.getElementById("costPerMap")?.value ?? "0",
    rows
  };

  localStorage.setItem("poe2FarmState", JSON.stringify(state));
}

function loadState(){
  const raw = localStorage.getItem("poe2FarmState");
  if (!raw) return;

  try{
    const s = JSON.parse(raw);

    if (s.activeSection) activeSection = s.activeSection;
    if (document.getElementById("marketSearch")) document.getElementById("marketSearch").value = s.search ?? "";

    if (document.getElementById("maps")) document.getElementById("maps").value = s.maps ?? "10";
    if (document.getElementById("costPerMap")) document.getElementById("costPerMap").value = s.costPerMap ?? "0";

    document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
    renderMarket();

    // restore loot rows
    const body = document.getElementById("lootBody");
    body.innerHTML = "";

    if (Array.isArray(s.rows) && s.rows.length){
      s.rows.forEach(r => {
        if (r.manual){
          addManualRow();
          const last = body.lastElementChild;
          last.querySelector(".lootItem").value = r.item || "";
          last.querySelector(".lootQty").value = r.qty ?? "0";
          last.querySelector(".manualPrice").value = r.price ?? "0";
        } else {
          addLootRow(r.item || "");
          const last = body.lastElementChild;
          last.querySelector(".lootQty").value = r.qty ?? "0";
          // price auto applied
        }
      });
    }

  }catch{}
}

function resetAll(){
  localStorage.removeItem("poe2FarmState");
  document.getElementById("maps").value = "10";
  document.getElementById("costPerMap").value = "0";

  document.getElementById("lootBody").innerHTML = "";
  addLootRow();

  activeSection = "currency";
  document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
  document.getElementById("marketSearch").value = "";
  renderMarket();

  recalcAll();
  setStatus("Status: reset ✅");
}

document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("marketSearch")?.addEventListener("input", () => { renderMarket(); saveState(); });

  document.getElementById("maps")?.addEventListener("input", () => { recalcAll(); saveState(); });
  document.getElementById("costPerMap")?.addEventListener("input", () => { recalcAll(); saveState(); });

  document.getElementById("resetBtn")?.addEventListener("click", resetAll);

  // ✅ IMPORTANT: we wrap handlers so no PointerEvent goes into addLootRow
  document.getElementById("addRowBtn")?.addEventListener("click", () => addLootRow());
  document.getElementById("addManualBtn")?.addEventListener("click", () => addManualRow());

  loadData();
});

// expose if needed
window.addLootRow = addLootRow;
window.addManualRow = addManualRow;
window.resetAll = resetAll;
