// ==============================
// PoE2 Farm Calculator (FINAL)
// Reads data/prices.json generated by scraper
// ==============================

let data = null;
let items = [];          // all lines
let sections = [];       // tabs
let byName = new Map();  // nameLower -> item

let activeTab = "currency";

let exaltIcon = "";
let divineIcon = "";
let divineInEx = null; // 1 Divine = X Ex (from Divine Orb row when value=exalted)

function setStatus(msg){
  const el = document.getElementById("fetchStatus");
  if (el) el.textContent = msg;
  console.log(msg);
}

function cleanName(s){
  return String(s || "").replace(/\s*WIKI\s*$/i, "").trim();
}

function escapeHtml(s){
  return String(s).replace(/[&<>"']/g, m => ({
    "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"
  }[m]));
}

function num(id){
  const el = document.getElementById(id);
  const v = el ? Number(el.value) : 0;
  return Number.isFinite(v) ? v : 0;
}

// ---------- Display helpers ----------
function formatExOrDiv(exValue){
  const ex = Number(exValue || 0);

  // If we know Divine price, display in Divine when large
  if (divineInEx && divineInEx > 0 && ex >= divineInEx) {
    const div = ex / divineInEx;
    return `
      <span>${div.toFixed(2)}</span>
      ${divineIcon ? `<img class="pIcon" src="${divineIcon}" alt="">` : ""}
    `;
  }

  return `
    <span>${ex.toFixed(2)}</span>
    ${exaltIcon ? `<img class="pIcon" src="${exaltIcon}" alt="">` : ""}
  `;
}

// Totals always show Ex + Div
function formatDual(exValue){
  const ex = Number(exValue || 0);
  const div = (divineInEx && divineInEx > 0) ? (ex / divineInEx) : 0;

  return `
    <span>${ex.toFixed(2)}</span>${exaltIcon ? `<img class="pIcon" src="${exaltIcon}" alt="">` : ""}
    <span style="opacity:.6;">/</span>
    <span>${div.toFixed(2)}</span>${divineIcon ? `<img class="pIcon" src="${divineIcon}" alt="">` : ""}
  `;
}

// ---------- Load JSON ----------
async function loadData(){
  try{
    setStatus("Status: loading data/prices.json...");

    const res = await fetch("./data/prices.json?ts=" + Date.now(), { cache:"no-store" });
    data = await res.json();

    sections = Array.isArray(data.sections) ? data.sections : [];
    items = Array.isArray(data.lines) ? data.lines : [];

    // normalize
    items = items.map(x => ({
      section: x.section || "currency",
      name: cleanName(x.name),
      icon: x.icon || "",
      amount: Number(x.amount ?? 0),       // amount is EXALTED because we scrape value=exalted
      unit: cleanName(x.unit || "Exalted Orb"),
      unitIcon: x.unitIcon || "",
    }));

    byName = new Map(items.map(x => [x.name.toLowerCase(), x]));

    // icons
    // base icon
    exaltIcon = data.baseIcon || byName.get("exalted orb")?.icon || "";
    // divine icon & divine price in exalt
    divineIcon = byName.get("divine orb")?.icon || "";
    divineInEx = byName.get("divine orb")?.amount || null;

    // build datalist
    fillDatalist();

    // bind UI
    bindTabs();
    bindInputs();

    // render
    renderMarket();
    loadState();

    // ensure 1 loot row
    if (!document.querySelector("#lootBody tr")) addLootRow();

    recalcAll();

    setStatus(`Status: OK ✅ sections=${sections.length || 13} items=${items.length} | 1 Div=${divineInEx ? divineInEx.toFixed(2) : "?"} Ex`);
  } catch(e){
    setStatus("Status: ERROR ❌ " + e.toString());
  }
}

// ---------- Tabs ----------
function bindTabs(){
  document.querySelectorAll(".tab").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab").forEach(b => b.classList.remove("active"));
      btn.classList.add("active");
      activeTab = btn.dataset.tab || "currency";
      renderMarket();
      saveState();
    });
  });
}

// ---------- Inputs / buttons ----------
function bindInputs(){
  document.getElementById("marketSearch")?.addEventListener("input", renderMarket);

  ["maps", "costPerMap"].forEach(id => {
    document.getElementById(id)?.addEventListener("input", () => {
      recalcAll();
      saveState();
    });
  });

  document.getElementById("resetBtn")?.addEventListener("click", resetAll);

  document.getElementById("addRowBtn")?.addEventListener("click", addLootRow);
  document.getElementById("addManualBtn")?.addEventListener("click", addManualRow);

  // expose if needed
  window.addLootRow = addLootRow;
  window.addManualRow = addManualRow;
  window.resetAll = resetAll;
}

// ---------- Market render ----------
function renderMarket(){
  const box = document.getElementById("marketList");
  if (!box) return;

  const q = (document.getElementById("marketSearch")?.value || "").trim().toLowerCase();
  box.innerHTML = "";

  const filtered = items
    .filter(x => x.section === activeTab)
    .filter(x => x.name.toLowerCase().includes(q))
    .slice(0, 400);

  if (!filtered.length){
    box.innerHTML = `<div style="padding:10px;color:#bbb;">No items.</div>`;
    return;
  }

  filtered.forEach(x => {
    const row = document.createElement("div");
    row.className = "market-row";
    row.innerHTML = `
      <div class="mLeft">
        ${x.icon ? `<img class="mIcon" src="${x.icon}" alt="">` : ""}
        <span class="mName">${escapeHtml(x.name)}</span>
      </div>
      <div class="mRight">
        ${formatExOrDiv(x.amount)}
      </div>
    `;

    row.addEventListener("click", () => {
      addLootRow(x.name);
    });

    box.appendChild(row);
  });
}

function fillDatalist(){
  const dl = document.getElementById("itemDatalist");
  if (!dl) return;
  dl.innerHTML = "";
  items.forEach(x => {
    const opt = document.createElement("option");
    opt.value = x.name;
    dl.appendChild(opt);
  });
}

// ---------- Loot rows ----------
function addLootRow(prefillName=""){
  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <img class="lootIcon" alt="">
        <input class="lootItem" list="itemDatalist" placeholder="Item">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <span class="lootPrice">0.00</span>
        ${exaltIcon ? `<img class="baseIcon" src="${exaltIcon}" alt="">` : ""}
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const itemInput = tr.querySelector(".lootItem");
  const qtyInput  = tr.querySelector(".lootQty");
  const iconImg   = tr.querySelector(".lootIcon");
  const priceSpan = tr.querySelector(".lootPrice");

  itemInput.value = prefillName || "";

  function applyPrice(){
    const name = (itemInput.value || "").trim().toLowerCase();
    const found = byName.get(name);

    if (found?.icon){
      iconImg.src = found.icon;
      iconImg.style.display = "block";
    } else {
      iconImg.style.display = "none";
    }

    const ex = found ? Number(found.amount || 0) : 0;
    priceSpan.textContent = ex.toFixed(2);
  }

  // initial
  applyPrice();
  recalcAll();
  saveState();

  // events
  itemInput.addEventListener("input", () => {
    applyPrice();
    recalcAll();
    saveState();
  });

  qtyInput.addEventListener("input", () => {
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    recalcAll();
    saveState();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    recalcAll();
    saveState();
  });
}

function addManualRow(){
  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow manualRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <span style="opacity:.6;">★</span>
        <input class="lootItem" placeholder="Custom name">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <input class="manualPrice" type="number" value="0" min="0" step="0.01" style="width:110px;">
        ${exaltIcon ? `<img class="baseIcon" src="${exaltIcon}" alt="">` : ""}
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const qtyInput = tr.querySelector(".lootQty");

  tr.querySelector(".manualPrice").addEventListener("input", () => { recalcAll(); saveState(); });
  qtyInput.addEventListener("input", () => { recalcAll(); saveState(); });

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    recalcAll();
    saveState();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    recalcAll();
    saveState();
  });

  recalcAll();
  saveState();
}

// ---------- Calculations ----------
function calcInvestEx(){
  return num("maps") * num("costPerMap");
}

function calcLootEx(){
  let total = 0;

  document.querySelectorAll("#lootBody tr").forEach(tr => {
    const qty = Number(tr.querySelector(".lootQty")?.value || 0);

    if (tr.classList.contains("manualRow")){
      const p = Number(tr.querySelector(".manualPrice")?.value || 0);
      total += p * qty;
    } else {
      const p = Number(tr.querySelector(".lootPrice")?.textContent || 0);
      total += p * qty;
    }
  });

  return total;
}

function recalcAll(){
  const invest = calcInvestEx();
  const loot = calcLootEx();
  const gain = loot - invest;

  document.getElementById("totalInvest").innerHTML = formatDual(invest);
  document.getElementById("totalLoot").innerHTML = formatDual(loot);
  document.getElementById("gain").innerHTML = formatDual(gain);
}

// ---------- Storage ----------
function saveState(){
  const rows = [...document.querySelectorAll("#lootBody tr")].map(tr => {
    const manual = tr.classList.contains("manualRow");
    return {
      manual,
      item: tr.querySelector(".lootItem")?.value || "",
      qty: Number(tr.querySelector(".lootQty")?.value || 0),
      price: manual ? Number(tr.querySelector(".manualPrice")?.value || 0) : null
    };
  });

  const invest = {
    maps: document.getElementById("maps")?.value ?? "10",
    costPerMap: document.getElementById("costPerMap")?.value ?? "0",
  };

  localStorage.setItem("poe2FarmState", JSON.stringify({ rows, invest, activeTab }));
}

function loadState(){
  const raw = localStorage.getItem("poe2FarmState");
  if (!raw) return;

  try{
    const st = JSON.parse(raw);

    if (st?.invest){
      document.getElementById("maps").value = st.invest.maps ?? "10";
      document.getElementById("costPerMap").value = st.invest.costPerMap ?? "0";
    }

    if (st?.activeTab){
      activeTab = st.activeTab;
      document.querySelectorAll(".tab").forEach(b => b.classList.toggle("active", b.dataset.tab === activeTab));
    }

    if (Array.isArray(st?.rows)){
      document.getElementById("lootBody").innerHTML = "";
      st.rows.forEach(r => {
        if (r.manual){
          addManualRow();
          const last = document.querySelector("#lootBody tr:last-child");
          last.querySelector(".lootItem").value = r.item || "";
          last.querySelector(".lootQty").value = r.qty ?? 0;
          last.querySelector(".manualPrice").value = r.price ?? 0;
        } else {
          addLootRow(r.item || "");
          const last = document.querySelector("#lootBody tr:last-child");
          last.querySelector(".lootQty").value = r.qty ?? 0;
        }
      });
    }

    renderMarket();
  } catch {}
}

// ---------- Reset ----------
function resetAll(){
  localStorage.removeItem("poe2FarmState");

  document.getElementById("maps").value = "10";
  document.getElementById("costPerMap").value = "0";

  document.getElementById("lootBody").innerHTML = "";
  addLootRow();

  activeTab = "currency";
  document.querySelectorAll(".tab").forEach(b => b.classList.toggle("active", b.dataset.tab === activeTab));

  document.getElementById("marketSearch").value = "";
  renderMarket();
  recalcAll();
  setStatus("Status: reset ✅");
}

// ---------- Init ----------
document.addEventListener("DOMContentLoaded", () => {
  loadData();
});
