// =======================
// PoE2 Farm Calculator - Stable UI + No PointerEvent bug
// Uses data/prices.json generated by scraper
// =======================

let allItems = [];           // full lines from prices.json
let byName = new Map();      // nameLower -> item
let activeSection = "currency";

let exaltIcon = "";
let divineIcon = "";
let divineExValue = null;    // 1 Divine = X Exalted (from prices.json)

let lastEditedCost = "ex";   // "ex" | "div"
let isSyncingCost = false;

const SECTIONS = [
  { id:"currency", label:"Currency" },
  { id:"fragments", label:"Fragments" },
  { id:"abyssalBones", label:"Abyssal Bones" },
  { id:"uncutGems", label:"Uncut Gems" },
  { id:"lineageGems", label:"Lineage Gems" },
  { id:"essences", label:"Essences" },
  { id:"soulCores", label:"Soul Cores" },
  { id:"idols", label:"Idols" },
  { id:"runes", label:"Runes" },
  { id:"omens", label:"Omens" },
  { id:"expedition", label:"Expedition" },
  { id:"liquidEmotions", label:"Liquid Emotions" },
  { id:"catalyst", label:"Catalyst" },
];

function setStatus(msg){
  const el = document.getElementById("fetchStatus");
  if (el) el.textContent = msg;
  console.log(msg);
}

function cleanName(s){
  return String(s || "").replace(/\s*WIKI\s*$/i, "").trim();
}

function num(id){
  const el = document.getElementById(id);
  const v = el ? Number(el.value) : 0;
  return Number.isFinite(v) ? v : 0;
}

function escapeHtml(s){
  return String(s).replace(/[&<>"']/g, m => ({
    "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"
  }[m]));
}

// ✅ No commas: always show numbers with DOT
function fmt2(n){
  const x = Number(n || 0);
  return x.toFixed(2);
}

function fmtDateTime(iso){
  if (!iso) return "";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return String(iso);
  const pad = (x)=> String(x).padStart(2,"0");
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

// --- display rule: if >= (1 Div + 1 Ex) => show in Div for user display
function shouldShowDiv(exAmount){
  if (!divineExValue || divineExValue <= 0) return false;
  return Number(exAmount || 0) >= (divineExValue + 1);
}

function setDualPriceDisplay(valueEl, iconEl, exAmount){
  const ex = Number(exAmount || 0);

  if (shouldShowDiv(ex) && divineIcon && divineExValue){
    valueEl.textContent = fmt2(ex / divineExValue);
    if (iconEl) iconEl.src = divineIcon;
  } else {
    valueEl.textContent = fmt2(ex);
    if (iconEl) iconEl.src = exaltIcon || "";
  }
}

// totals show Ex/Div both
function formatDual(exVal){
  const ex = Number(exVal || 0);
  const div = (divineExValue && divineExValue > 0) ? (ex / divineExValue) : 0;

  return `
    <span>${fmt2(ex)}</span>${exaltIcon ? `<img class="pIcon" src="${exaltIcon}" alt="">` : ""}
    <span style="opacity:.6">/</span>
    <span>${fmt2(div)}</span>${divineIcon ? `<img class="pIcon" src="${divineIcon}" alt="">` : ""}
  `;
}

async function loadData(){
  try{
    setStatus("Status: loading data/prices.json...");
    const res = await fetch("./data/prices.json?ts=" + Date.now(), { cache:"no-store" });
    const data = await res.json();

    allItems = (data.lines || []).map(x => ({
      section: x.section || "currency",
      name: cleanName(x.name),
      icon: x.icon || "",
      amount: Number(x.amount ?? 0),   // stored in Exalted
      unit: x.unit || "",
      unitIcon: x.unitIcon || "",
    }));

    byName = new Map(allItems.map(it => [it.name.toLowerCase(), it]));

    exaltIcon = data.baseIcon || "";
    const divRow = byName.get("divine orb");
    divineIcon = divRow?.icon || "";
    divineExValue = divRow ? Number(divRow.amount || 0) : null;

    const updatedAt = data.updatedAt || "";
    const updatedStr = updatedAt ? ` | last scrape=${fmtDateTime(updatedAt)}` : "";
    setStatus(`Status: OK ✅ sections=${SECTIONS.length} items=${allItems.length} | 1 Div=${divineExValue ?? "?"} Ex${updatedStr}`);

    buildTabs();
    fillDatalist();
    renderMarket();
    loadState();

    // sync cost fields once we know divineExValue
    syncCostFields();

    // ensure at least one loot row
    if (!document.querySelector("#lootBody tr")) addLootRow();
    recalcAll();

  }catch(e){
    setStatus("Status: ERROR ❌ " + e.toString());
  }
}

function buildTabs(){
  const wrap = document.getElementById("tabs");
  if (!wrap) return;

  wrap.innerHTML = "";
  SECTIONS.forEach(sec => {
    const b = document.createElement("button");
    b.className = "tab" + (sec.id === activeSection ? " active" : "");
    b.textContent = sec.label;
    b.dataset.tab = sec.id;

    b.addEventListener("click", () => {
      activeSection = sec.id;
      document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
      renderMarket();
      saveState();
    });

    wrap.appendChild(b);
  });
}

function fillDatalist(){
  const dl = document.getElementById("itemDatalist");
  if (!dl) return;

  dl.innerHTML = "";
  allItems.forEach(it => {
    const opt = document.createElement("option");
    opt.value = it.name;
    dl.appendChild(opt);
  });
}

function renderMarket(){
  const list = document.getElementById("marketList");
  if (!list) return;

  const q = (document.getElementById("marketSearch")?.value || "").trim().toLowerCase();

  const filtered = allItems
    .filter(it => it.section === activeSection)
    .filter(it => it.name.toLowerCase().includes(q))
    .slice(0, 300);

  list.innerHTML = "";

  if (!filtered.length){
    list.innerHTML = `<div style="color:#bbb;padding:10px;">No items.</div>`;
    return;
  }

  filtered.forEach(it => {
    const row = document.createElement("div");
    row.className = "market-row";

    row.innerHTML = `
      <div class="mLeft">
        ${it.icon ? `<img class="cIcon" src="${it.icon}" alt="">` : ""}
        <span class="mName">${escapeHtml(it.name)}</span>
      </div>

      <div class="mArrow">⇄</div>

      <div class="mRight">
        <span class="mPriceVal">0.00</span>
        <img class="unitIcon" alt="">
      </div>
    `;

    const valEl = row.querySelector(".mPriceVal");
    const icoEl = row.querySelector(".unitIcon");
    setDualPriceDisplay(valEl, icoEl, it.amount);

    row.addEventListener("click", () => addLootRow(it.name));
    list.appendChild(row);
  });
}

// ✅ FIXED: will never put PointerEvent into input
function addLootRow(prefillName = ""){
  if (prefillName && typeof prefillName === "object") prefillName = "";
  prefillName = String(prefillName || "");

  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <img class="lootIcon" alt="">
        <input class="lootItem" list="itemDatalist" placeholder="Item">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <span class="lootPrice" data-ex="0">0.00</span>
        <img class="baseIcon" alt="">
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus" aria-label="Minus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus" aria-label="Plus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const itemInput = tr.querySelector(".lootItem");
  const qtyInput  = tr.querySelector(".lootQty");
  const iconImg   = tr.querySelector(".lootIcon");
  const priceSpan = tr.querySelector(".lootPrice");
  const unitImg   = tr.querySelector(".baseIcon");

  itemInput.value = prefillName;

  function applyPrice(){
    const name = (itemInput.value || "").trim().toLowerCase();
    const found = byName.get(name);

    if (found?.icon){
      iconImg.src = found.icon;
      iconImg.style.display = "block";
    } else {
      iconImg.style.display = "none";
    }

    const ex = Number(found ? found.amount : 0);
    priceSpan.dataset.ex = String(ex);

    // display rule (Div for big values)
    setDualPriceDisplay(priceSpan, unitImg, ex);
  }

  applyPrice();
  recalcAll();
  saveState();

  itemInput.addEventListener("input", () => {
    applyPrice();
    recalcAll();
    saveState();
  });

  qtyInput.addEventListener("input", () => {
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    recalcAll();
    saveState();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    recalcAll();
    saveState();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    recalcAll();
    saveState();
  });
}

function addManualRow(){
  const body = document.getElementById("lootBody");
  if (!body) return;

  const tr = document.createElement("tr");
  tr.className = "lootRow manualRow";

  tr.innerHTML = `
    <td>
      <div class="lootItemWrap">
        <img class="lootIcon" style="display:none" alt="">
        <input class="lootItem" placeholder="Custom item">
      </div>
    </td>

    <td>
      <div class="priceCell">
        <input class="manualPrice" type="number" value="0" min="0" step="0.01">
        ${exaltIcon ? `<img class="baseIcon" src="${exaltIcon}" alt="">` : `<img class="baseIcon" alt="">`}
      </div>
    </td>

    <td>
      <div class="qtyWrap">
        <button type="button" class="qtyBtn qtyMinus">−</button>
        <input class="lootQty" type="number" value="0" min="0">
        <button type="button" class="qtyBtn qtyPlus">+</button>
      </div>
    </td>

    <td><button type="button" class="deleteBtn" title="Delete">✖</button></td>
  `;

  body.appendChild(tr);

  const qtyInput = tr.querySelector(".lootQty");
  const priceInput = tr.querySelector(".manualPrice");

  const update = () => { recalcAll(); saveState(); };

  qtyInput.addEventListener("input", update);
  priceInput.addEventListener("input", update);

  tr.querySelector(".qtyMinus").addEventListener("click", () => {
    qtyInput.value = Math.max(0, (Number(qtyInput.value) || 0) - 1);
    update();
  });

  tr.querySelector(".qtyPlus").addEventListener("click", () => {
    qtyInput.value = (Number(qtyInput.value) || 0) + 1;
    update();
  });

  tr.querySelector(".deleteBtn").addEventListener("click", () => {
    tr.remove();
    update();
  });

  update();
}

// --- cost per map Ex/Div sync
function syncCostFields(){
  const exEl = document.getElementById("costPerMap");
  const divEl = document.getElementById("costPerMapDiv");
  if (!exEl || !divEl) return;

  if (!divineExValue || divineExValue <= 0) {
    // no conversion possible yet
    return;
  }

  isSyncingCost = true;
  if (lastEditedCost === "div"){
    const div = Number(divEl.value || 0);
    exEl.value = fmt2(div * divineExValue);
  } else {
    const ex = Number(exEl.value || 0);
    divEl.value = fmt2(ex / divineExValue);
  }
  isSyncingCost = false;
}

function calcInvestEx(){
  const maps = num("maps");
  const exEl = document.getElementById("costPerMap");
  const divEl = document.getElementById("costPerMapDiv");

  const exCost = exEl ? Number(exEl.value || 0) : 0;
  const divCost = divEl ? Number(divEl.value || 0) : 0;

  let costEx = exCost;
  if (lastEditedCost === "div" && divineExValue && divineExValue > 0){
    costEx = divCost * divineExValue;
  }
  return maps * (Number(costEx) || 0);
}

function calcLootEx(){
  let total = 0;
  document.querySelectorAll("#lootBody tr").forEach(tr => {
    const qty = Number(tr.querySelector(".lootQty")?.value || 0);

    if (tr.classList.contains("manualRow")){
      const p = Number(tr.querySelector(".manualPrice")?.value || 0);
      total += p * qty;
    } else {
      const ex = Number(tr.querySelector(".lootPrice")?.dataset?.ex || 0);
      total += ex * qty;
    }
  });
  return total;
}

function recalcAll(){
  const invest = calcInvestEx();
  const loot = calcLootEx();
  const gain = loot - invest;

  document.getElementById("totalInvest").innerHTML = formatDual(invest);
  document.getElementById("totalLoot").innerHTML = formatDual(loot);
  document.getElementById("gain").innerHTML = formatDual(gain);
}

function exportLootCSV(){
  const rows = [];
  document.querySelectorAll("#lootBody tr").forEach(tr => {
    const item = (tr.querySelector(".lootItem")?.value || "").trim();
    const qty = Number(tr.querySelector(".lootQty")?.value || 0);

    let priceEx = 0;
    if (tr.classList.contains("manualRow")){
      priceEx = Number(tr.querySelector(".manualPrice")?.value || 0);
    } else {
      priceEx = Number(tr.querySelector(".lootPrice")?.dataset?.ex || 0);
    }

    if (!item && qty === 0 && priceEx === 0) return;

    rows.push({
      item,
      qty,
      priceEx,
      totalEx: priceEx * qty
    });
  });

  const header = ["Item","Qty","Price (Ex)","Total (Ex)"];
  const escapeCSV = (s) => {
    const str = String(s ?? "");
    return /[",\n]/.test(str) ? `"${str.replace(/"/g,'""')}"` : str;
  };

  const csv = [
    header.join(","),
    ...rows.map(r => [
      escapeCSV(r.item),
      r.qty,
      fmt2(r.priceEx),
      fmt2(r.totalEx)
    ].join(","))
  ].join("\n");

  const blob = new Blob([csv], { type:"text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `poe2_loot_${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function saveState(){
  const rows = [...document.querySelectorAll("#lootBody tr")].map(tr => {
    const manual = tr.classList.contains("manualRow");
    return {
      manual,
      item: tr.querySelector(".lootItem")?.value || "",
      qty: tr.querySelector(".lootQty")?.value ?? "0",
      price: manual ? (tr.querySelector(".manualPrice")?.value ?? "0") : null
    };
  });

  const state = {
    activeSection,
    search: document.getElementById("marketSearch")?.value ?? "",
    maps: document.getElementById("maps")?.value ?? "10",
    costPerMap: document.getElementById("costPerMap")?.value ?? "0",
    costPerMapDiv: document.getElementById("costPerMapDiv")?.value ?? "0",
    lastEditedCost,
    rows
  };

  localStorage.setItem("poe2FarmState", JSON.stringify(state));
}

function loadState(){
  const raw = localStorage.getItem("poe2FarmState");
  if (!raw) return;

  try{
    const s = JSON.parse(raw);

    if (s.activeSection) activeSection = s.activeSection;
    if (document.getElementById("marketSearch")) document.getElementById("marketSearch").value = s.search ?? "";

    if (document.getElementById("maps")) document.getElementById("maps").value = s.maps ?? "10";
    if (document.getElementById("costPerMap")) document.getElementById("costPerMap").value = s.costPerMap ?? "0";
    if (document.getElementById("costPerMapDiv")) document.getElementById("costPerMapDiv").value = s.costPerMapDiv ?? "0";
    if (s.lastEditedCost) lastEditedCost = s.lastEditedCost;

    document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
    renderMarket();

    // restore loot rows
    const body = document.getElementById("lootBody");
    body.innerHTML = "";

    if (Array.isArray(s.rows) && s.rows.length){
      s.rows.forEach(r => {
        if (r.manual){
          addManualRow();
          const last = body.lastElementChild;
          last.querySelector(".lootItem").value = r.item || "";
          last.querySelector(".lootQty").value = r.qty ?? "0";
          last.querySelector(".manualPrice").value = r.price ?? "0";
        } else {
          addLootRow(r.item || "");
          const last = body.lastElementChild;
          last.querySelector(".lootQty").value = r.qty ?? "0";
        }
      });
    }

  }catch{}
}

function resetAll(){
  localStorage.removeItem("poe2FarmState");
  document.getElementById("maps").value = "10";
  document.getElementById("costPerMap").value = "0";
  document.getElementById("costPerMapDiv").value = "0";
  lastEditedCost = "ex";

  document.getElementById("lootBody").innerHTML = "";
  addLootRow();

  activeSection = "currency";
  document.querySelectorAll(".tab").forEach(x => x.classList.toggle("active", x.dataset.tab === activeSection));
  document.getElementById("marketSearch").value = "";
  renderMarket();

  recalcAll();
  setStatus("Status: reset ✅");
}

document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("marketSearch")?.addEventListener("input", () => { renderMarket(); saveState(); });

  document.getElementById("maps")?.addEventListener("input", () => { recalcAll(); saveState(); });

  document.getElementById("costPerMap")?.addEventListener("input", () => {
    if (isSyncingCost) return;
    lastEditedCost = "ex";
    syncCostFields();
    recalcAll();
    saveState();
  });

  document.getElementById("costPerMapDiv")?.addEventListener("input", () => {
    if (isSyncingCost) return;
    lastEditedCost = "div";
    syncCostFields();
    recalcAll();
    saveState();
  });

  document.getElementById("resetBtn")?.addEventListener("click", resetAll);

  document.getElementById("exportCsvBtn")?.addEventListener("click", exportLootCSV);

  loadData();
});

// expose if needed
window.addLootRow = addLootRow;
window.addManualRow = addManualRow;
window.resetAll = resetAll;
